#!/bin/sh

if [ ! -d ".vim/backup" ]; then
    mkdir .vim/backup
fi

curl -L http://install.ohmyz.sh | sh

# bug if no not use sh -c
# see: http://www.fan.gr.jp/~azure/diary/dia201002.html#n20100224
sh -c "rsync -avz --no-o --no-g -c \
    --exclude=*.swp \
    --exclude=.git \
    --exclude=$(basename $0) . ~/"

sed -i 's/ZSH_THEME=.*$/ZSH_THEME="gallifrey"/' ~/.zshrc
sed -i 's/plugins=.*$/plugins=(git tmux-ssh-agent)/' ~/.zshrc
sed -i 's/^\s*#\s*(DISABLE_AUTO_UPDATE=.*)$/\\1/g' ~/.zshrc
