#!/bin/sh

curl -L http://install.ohmyz.sh | sh

BASE_DIR=$(basename $0)

# bug if no not use sh -c
# see: http://www.fan.gr.jp/~azure/diary/dia201002.html#n20100224
sh -c "rsync -avz --no-o --no-g -c \
    --exclude=*.swp \
    --exclude=.git \
    --exclude=$BASE_DIR . ~/"

grep 'ZSH_THEME="gallifrey"' ~/.zshrc >& /dev/null
if [ $? -gt 0 ]; then
    sed -i 's/ZSH_THEME=.*$/ZSH_THEME="gallifrey"/' ~/.zshrc
fi

grep tmux-ssh-agent ~/.zshrc >& /dev/null
if [ $? -gt 0 ]; then
    sed -i "s/^\(plugins=.*\)\()\)/\1 tmux-ssh-agent\2/" ~/.zshrc
fi

if grep "^#\s*DISABLE_AUTO_TITLE" ~/.zshrc >& /dev/null; then
    sed -i "s/#\s*\(DISABLE_AUTO_TITLE=.*\)/\1/" ~/.zshrc
fi
